// src/lib/constants.server.ts
import { env } from '#/lib/env.lib.server'
import type { UdemySelectors } from '#/types/api.type'
import {
  DEFAULT_NOTES_CONTAINER_SELECTOR,
  DEFAULT_NOTE_SELECTOR,
  DEFAULT_DURATION_SELECTOR,
  DEFAULT_SECTION_SELECTOR,
  DEFAULT_LECTURE_SELECTOR,
  DEFAULT_NOTE_BODY_SELECTOR,
  DEFAULT_NOTE_CODE_BLOCK_SELECTOR,
  DEFAULT_COURSE_HEAD_TITLE_SELECTOR,
  DEFAULT_COURSE_OG_TITLE_SELECTOR,
  DEFAULT_COURSE_META_TITLE_SELECTOR,
  DEFAULT_COURSE_META_DESCRIPTION_SELECTOR,
  DEFAULT_COURSE_OG_DESCRIPTION_SELECTOR,
  DEFAULT_COURSE_IMAGE_URL_SELECTOR,
  DEFAULT_COURSE_URL_SELECTOR,
  DEFAULT_TRAINER_URL_SELECTOR,
  DEFAULT_SERVER_ERROR_SANITIZED_MESSAGE,
} from '#/lib/defaults.lib'

export const UDEMY_SELECTORS: UdemySelectors = {
  notesContainerSelector:
    env.NOTES_CONTAINER_SELECTOR || DEFAULT_NOTES_CONTAINER_SELECTOR,
  noteSelector: env.NOTE_SELECTOR || DEFAULT_NOTE_SELECTOR,
  durationSelector: env.DURATION_SELECTOR || DEFAULT_DURATION_SELECTOR,
  sectionSelector: env.SECTION_SELECTOR || DEFAULT_SECTION_SELECTOR,
  lectureSelector: env.LECTURE_SELECTOR || DEFAULT_LECTURE_SELECTOR,
  noteBodySelector: env.NOTE_BODY_SELECTOR || DEFAULT_NOTE_BODY_SELECTOR,
  noteCodeBlockSelector:
    env.NOTE_CODE_BLOCK_SELECTOR || DEFAULT_NOTE_CODE_BLOCK_SELECTOR,
  courseUrlSelector: env.COURSE_URL_SELECTOR || DEFAULT_COURSE_URL_SELECTOR,
  headTitleSelector:
    env.COURSE_HEAD_TITLE_SELECTOR || DEFAULT_COURSE_HEAD_TITLE_SELECTOR,
  ogTitleSelector:
    env.COURSE_OG_TITLE_SELECTOR || DEFAULT_COURSE_OG_TITLE_SELECTOR,
  metaTitleSelector:
    env.COURSE_META_TITLE_SELECTOR || DEFAULT_COURSE_META_TITLE_SELECTOR,
  metaDescriptionSelector:
    env.COURSE_META_DESCRIPTION_SELECTOR ||
    DEFAULT_COURSE_META_DESCRIPTION_SELECTOR,
  ogDescriptionSelector:
    env.COURSE_OG_DESCRIPTION_SELECTOR ||
    DEFAULT_COURSE_OG_DESCRIPTION_SELECTOR,
  imageUrlSelector:
    env.COURSE_IMAGE_URL_SELECTOR || DEFAULT_COURSE_IMAGE_URL_SELECTOR,
  trainerUrlSelector: env.TRAINER_URL_SELECTOR || DEFAULT_TRAINER_URL_SELECTOR,
}

export const EXAMPLE_SIGNING_SECRET = 'udemy-notes-secure-metadata'
export const SIGNING_SECRET = env.SIGNING_SECRET || EXAMPLE_SIGNING_SECRET
export const SERVER_ERROR_SANITIZED_MESSAGE =
  env.SERVER_ERROR_SANITIZED_MESSAGE || DEFAULT_SERVER_ERROR_SANITIZED_MESSAGE
