/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContentRouteRouteImport } from './routes/_content/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContentTagsIndexRouteImport } from './routes/_content/tags/index'
import { Route as ContentNotesIndexRouteImport } from './routes/_content/notes/index'
import { Route as ContentCoursesIndexRouteImport } from './routes/_content/courses/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup.index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ContentCoursesImportIndexRouteImport } from './routes/_content/courses/import.index'
import { Route as ContentCoursesCourseIdIndexRouteImport } from './routes/_content/courses/$courseId.index'

const ContentRouteRoute = ContentRouteRouteImport.update({
  id: '/_content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTagsIndexRoute = ContentTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ContentRouteRoute,
} as any)
const ContentNotesIndexRoute = ContentNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => ContentRouteRoute,
} as any)
const ContentCoursesIndexRoute = ContentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ContentRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/_auth/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCoursesImportIndexRoute =
  ContentCoursesImportIndexRouteImport.update({
    id: '/courses/import/',
    path: '/courses/import/',
    getParentRoute: () => ContentRouteRoute,
  } as any)
const ContentCoursesCourseIdIndexRoute =
  ContentCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => ContentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/courses/': typeof ContentCoursesIndexRoute
  '/notes/': typeof ContentNotesIndexRoute
  '/tags/': typeof ContentTagsIndexRoute
  '/courses/$courseId/': typeof ContentCoursesCourseIdIndexRoute
  '/courses/import/': typeof ContentCoursesImportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/courses': typeof ContentCoursesIndexRoute
  '/notes': typeof ContentNotesIndexRoute
  '/tags': typeof ContentTagsIndexRoute
  '/courses/$courseId': typeof ContentCoursesCourseIdIndexRoute
  '/courses/import': typeof ContentCoursesImportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_content': typeof ContentRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_content/courses/': typeof ContentCoursesIndexRoute
  '/_content/notes/': typeof ContentNotesIndexRoute
  '/_content/tags/': typeof ContentTagsIndexRoute
  '/_content/courses/$courseId/': typeof ContentCoursesCourseIdIndexRoute
  '/_content/courses/import/': typeof ContentCoursesImportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/login/'
    | '/signup/'
    | '/courses/'
    | '/notes/'
    | '/tags/'
    | '/courses/$courseId/'
    | '/courses/import/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/login'
    | '/signup'
    | '/courses'
    | '/notes'
    | '/tags'
    | '/courses/$courseId'
    | '/courses/import'
  id:
    | '__root__'
    | '/'
    | '/_content'
    | '/dashboard/'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/_content/courses/'
    | '/_content/notes/'
    | '/_content/tags/'
    | '/_content/courses/$courseId/'
    | '/_content/courses/import/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRouteRoute: typeof ContentRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_content': {
      id: '/_content'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ContentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content/tags/': {
      id: '/_content/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof ContentTagsIndexRouteImport
      parentRoute: typeof ContentRouteRoute
    }
    '/_content/notes/': {
      id: '/_content/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof ContentNotesIndexRouteImport
      parentRoute: typeof ContentRouteRoute
    }
    '/_content/courses/': {
      id: '/_content/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof ContentCoursesIndexRouteImport
      parentRoute: typeof ContentRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content/courses/import/': {
      id: '/_content/courses/import/'
      path: '/courses/import'
      fullPath: '/courses/import/'
      preLoaderRoute: typeof ContentCoursesImportIndexRouteImport
      parentRoute: typeof ContentRouteRoute
    }
    '/_content/courses/$courseId/': {
      id: '/_content/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof ContentCoursesCourseIdIndexRouteImport
      parentRoute: typeof ContentRouteRoute
    }
  }
}

interface ContentRouteRouteChildren {
  ContentCoursesIndexRoute: typeof ContentCoursesIndexRoute
  ContentNotesIndexRoute: typeof ContentNotesIndexRoute
  ContentTagsIndexRoute: typeof ContentTagsIndexRoute
  ContentCoursesCourseIdIndexRoute: typeof ContentCoursesCourseIdIndexRoute
  ContentCoursesImportIndexRoute: typeof ContentCoursesImportIndexRoute
}

const ContentRouteRouteChildren: ContentRouteRouteChildren = {
  ContentCoursesIndexRoute: ContentCoursesIndexRoute,
  ContentNotesIndexRoute: ContentNotesIndexRoute,
  ContentTagsIndexRoute: ContentTagsIndexRoute,
  ContentCoursesCourseIdIndexRoute: ContentCoursesCourseIdIndexRoute,
  ContentCoursesImportIndexRoute: ContentCoursesImportIndexRoute,
}

const ContentRouteRouteWithChildren = ContentRouteRoute._addFileChildren(
  ContentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRouteRoute: ContentRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
